//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDealer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Contract = new HashSet<Contract>();
        }
    
        public int c_id { get; set; }
        public string c_mark { get; set; }
        public string c_name { get; set; }
        public string c_specific { get; set; }
        public byte[] c_photo { get; set; }
        public int c_tariff { get; set; }
        public int c_as { get; set; }
        public Nullable<int> c_employee { get; set; }
    
        public virtual AddService AddService { get; set; }
        public virtual Tariff Tariff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
    }
}
