//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDealer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int con_id { get; set; }
        public int con_long { get; set; }
        public string con_if { get; set; }
        public decimal con_cost { get; set; }
        public int con_car { get; set; }
        public int con_client { get; set; }
        public System.DateTime con_date { get; set; }
        public Nullable<double> con_sum { get; set; }
        public Nullable<System.DateTime> con_dateend { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Client Client { get; set; }
    }
}
