//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDealer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.LogUser = new HashSet<LogUser>();
        }
    
        public int e_id { get; set; }
        public string e_family { get; set; }
        public string e_name { get; set; }
        public string e_patronymic { get; set; }
        public System.DateTime e_birthday { get; set; }
        public int e_position { get; set; }
        public string e_passport { get; set; }

        public string e_all
        {
            get
            {
                return e_family + " " + e_name;
            }
        }

        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogUser> LogUser { get; set; }
    }
}
