//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDealer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogUser
    {
        public int lu_id { get; set; }
        public int lu_empl { get; set; }
        public string lu_login { get; set; }
        public string lu_password { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
